---
version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Japan/Osaka
    volumes:
      - /mnt/usb/Appdata/radarr/config:/config
      - /mnt/usb/Movies:/movies
      - /PATH/TO/FOLDER/Downloads/Movies:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
