version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000 #Add your PUID
      - PGID=1000 #Add your PGID
      - TZ=Japan/Kyoto
    volumes:
      - /path/to/Appdata/syncthing/config:/config
      - /path/to/Appdata/syncthing/sync:/data1
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
